/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { FunctionalRequirement } from "../../functionalRequirement/base/FunctionalRequirement";
import { LibraryFramework } from "../../libraryFramework/base/LibraryFramework";
import { EnumProjectTypeField } from "./EnumProjectTypeField";

@ObjectType()
class Project {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: () => [FunctionalRequirement],
  })
  @ValidateNested()
  @Type(() => FunctionalRequirement)
  @IsOptional()
  functionalRequirements?: Array<FunctionalRequirement>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [LibraryFramework],
  })
  @ValidateNested()
  @Type(() => LibraryFramework)
  @IsOptional()
  libraryFrameworks?: Array<LibraryFramework>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tools!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProjectTypeField,
  })
  @IsEnum(EnumProjectTypeField)
  @IsOptional()
  @Field(() => EnumProjectTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Project as Project };
