/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectService } from "../project.service";
import { ProjectCreateInput } from "./ProjectCreateInput";
import { Project } from "./Project";
import { ProjectFindManyArgs } from "./ProjectFindManyArgs";
import { ProjectWhereUniqueInput } from "./ProjectWhereUniqueInput";
import { ProjectUpdateInput } from "./ProjectUpdateInput";
import { FunctionalRequirementFindManyArgs } from "../../functionalRequirement/base/FunctionalRequirementFindManyArgs";
import { FunctionalRequirement } from "../../functionalRequirement/base/FunctionalRequirement";
import { FunctionalRequirementWhereUniqueInput } from "../../functionalRequirement/base/FunctionalRequirementWhereUniqueInput";
import { LibraryFrameworkFindManyArgs } from "../../libraryFramework/base/LibraryFrameworkFindManyArgs";
import { LibraryFramework } from "../../libraryFramework/base/LibraryFramework";
import { LibraryFrameworkWhereUniqueInput } from "../../libraryFramework/base/LibraryFrameworkWhereUniqueInput";

export class ProjectControllerBase {
  constructor(protected readonly service: ProjectService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Project })
  async createProject(
    @common.Body() data: ProjectCreateInput
  ): Promise<Project> {
    return await this.service.createProject({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        tools: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Project] })
  @ApiNestedQuery(ProjectFindManyArgs)
  async projects(@common.Req() request: Request): Promise<Project[]> {
    const args = plainToClass(ProjectFindManyArgs, request.query);
    return this.service.projects({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        tools: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async project(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    const result = await this.service.project({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        tools: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProject(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() data: ProjectUpdateInput
  ): Promise<Project | null> {
    try {
      return await this.service.updateProject({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          tools: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Project })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProject(
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<Project | null> {
    try {
      return await this.service.deleteProject({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          tools: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/functionalRequirements")
  @ApiNestedQuery(FunctionalRequirementFindManyArgs)
  async findFunctionalRequirements(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<FunctionalRequirement[]> {
    const query = plainToClass(
      FunctionalRequirementFindManyArgs,
      request.query
    );
    const results = await this.service.findFunctionalRequirements(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/functionalRequirements")
  async connectFunctionalRequirements(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: FunctionalRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      functionalRequirements: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/functionalRequirements")
  async updateFunctionalRequirements(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: FunctionalRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      functionalRequirements: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/functionalRequirements")
  async disconnectFunctionalRequirements(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: FunctionalRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      functionalRequirements: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/libraryFrameworks")
  @ApiNestedQuery(LibraryFrameworkFindManyArgs)
  async findLibraryFrameworks(
    @common.Req() request: Request,
    @common.Param() params: ProjectWhereUniqueInput
  ): Promise<LibraryFramework[]> {
    const query = plainToClass(LibraryFrameworkFindManyArgs, request.query);
    const results = await this.service.findLibraryFrameworks(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/libraryFrameworks")
  async connectLibraryFrameworks(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: LibraryFrameworkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      libraryFrameworks: {
        connect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/libraryFrameworks")
  async updateLibraryFrameworks(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: LibraryFrameworkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      libraryFrameworks: {
        set: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/libraryFrameworks")
  async disconnectLibraryFrameworks(
    @common.Param() params: ProjectWhereUniqueInput,
    @common.Body() body: LibraryFrameworkWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      libraryFrameworks: {
        disconnect: body,
      },
    };
    await this.service.updateProject({
      where: params,
      data,
      select: { id: true },
    });
  }
}
