/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FunctionalRequirementListRelationFilter } from "../../functionalRequirement/base/FunctionalRequirementListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { LibraryFrameworkListRelationFilter } from "../../libraryFramework/base/LibraryFrameworkListRelationFilter";
import { EnumProjectTypeField } from "./EnumProjectTypeField";

@InputType()
class ProjectWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FunctionalRequirementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FunctionalRequirementListRelationFilter)
  @IsOptional()
  @Field(() => FunctionalRequirementListRelationFilter, {
    nullable: true,
  })
  functionalRequirements?: FunctionalRequirementListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LibraryFrameworkListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LibraryFrameworkListRelationFilter)
  @IsOptional()
  @Field(() => LibraryFrameworkListRelationFilter, {
    nullable: true,
  })
  libraryFrameworks?: LibraryFrameworkListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tools?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumProjectTypeField,
  })
  @IsEnum(EnumProjectTypeField)
  @IsOptional()
  @Field(() => EnumProjectTypeField, {
    nullable: true,
  })
  typeField?: "Option1";
}

export { ProjectWhereInput as ProjectWhereInput };
